# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'fastlane-plugin-firebase_app_distribution'
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do |options|
    flutter_version = options[:flutter_version]
    sh "flutter run lib/main.dart"
  end

  desc "Deploy iOS build"
  lane :deployIOS do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store", # Bisa diganti dengan 'ad-hoc', 'development', atau 'enterprise'
      output_directory: "../build/ios/",
      output_name: "app.ipa"
    )

    firebase_app_distribution(
      app: "1:784716769060:ios:d478cfa77fc972ccbe75b1", # Ganti dengan Firebase App ID untuk iOS
      firebase_cli_path: "/opt/homebrew/bin/firebase",
      groups: "testers",
      ios_artifact_type: "IPA",
      ipa_path: "../build/ios/app.ipa",
      debug: true
    )
  end
end
