# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end


fastlane_require 'fastlane-plugin-firebase_app_distribution'
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do |options|
    flutter_version = options[:flutter_version]
    sh "flutter run lib/main.dart"
  end
# ---------------- 1st path -----------------------------
  desc "Deploy Android build"
  lane :deployAndroid do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      flags: '-Ptarget=lib/main.dart'
    )
# ---------------- 2nd path -----------------------------
    firebase_app_distribution(
      app: "1:784716769060:android:1613a12ff9192942be75b1",
      firebase_cli_path: "/opt/homebrew/bin/firebase",
      groups: "testers",
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      debug: true
    )
# ---------------- 3rd path -----------------------------
  end
end
